[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"] # Use Node.js and Yarn

# [phases.build]
# cmd = "pnpm install && pnpm build" # Install dependencies and build the app

[start]
cmd = "pnpm preview" # Start the app using Vite preview
